# This action installs packages for macOS

name: macOS Install Packages CLI
description: 'Install packages for macOS'

runs:
  using: "composite"
  steps:
      - name: Install Packages CLI
        run: |
          curl -L http://s.sudre.free.fr/Software/files/Packages.dmg -o Packages.dmg
          hdiutil mount Packages.dmg
          # Use a wildcard to handle "Packages 1.2.11" or any other version
          sudo installer -pkg /Volumes/Packages*/Install\ Packages.pkg -target /
          # Unmount using the same wildcard
          hdiutil unmount /Volumes/Packages*
        shell: bash
