# This action creates the XLingPaper configuration folder for Windows

name: Windows Create XLingPaper configuration folder
description: 'Creates the XLingPaper configuration folder for Windows'

runs:
  using: "composite"
  steps:
    - name: 'create XLingPaper Configuration Folder'
      run: |
        mkdir XLingPaperConfiguration
        cd XLingPaperConfiguration
        mkdir XLingPap
        xcopy /f /s /e /y /i ..\batchfiles XLingPap\batchfiles
        xcopy /f /s /e /y /i ..\configuration XLingPap\configuration
        xcopy /f /s /e /y /i ..\css XLingPap\css
        xcopy /f /s /e /y /i ..\doc XLingPap\doc
        xcopy /f /s /e /y /i ..\dtds XLingPap\dtds
        xcopy /f /s /e /y /i ..\externalPackages XLingPap\externalPackages
        xcopy /f /s /e /y /i ..\localizations XLingPap\localizations
        xcopy /f /s /e /y /i ..\publisherstylesheets XLingPap\publisherstylesheets
        xcopy /f /s /e /y /i ..\templates XLingPap\templates
        xcopy /f /s /e /y /i ..\transforms XLingPap\transforms
        copy ..\XLingPap.jar XLingPap
        copy ..\XLingPap.sch XLingPap
        copy ..\XLingPap.xxe XLingPap
        copy ..\xlingpap.xxe_addon XLingPap
        copy ..\XLingPap_catalog.xml XLingPap
      shell: cmd
