#XMLmind XML Editor Personal Edition 8.2.0
#Fri May 29 11:56:54 MST 2026
autoCheckForUpdates=false
autoSaveInterval=300
autoSaveTimeout=30
ensureSaveFileHasExtension=true
selectedLanguage=en
rightPanes.collapsed=false
rightTab.mathmlPane.index=1
rightTab.editAttributePane.atStart=false
rightTab.editPane.atStart=true
rightTab.insertCharacterPane.atStart=false
rightTab.editPane.selected=true
passwords=
rightTabs.horizontalRatio=0.4
addonDir=
wrapSearch=false
rightTab.checkValidityPane.atStart=false
rightTab.textSearchReplacePane.selected=false
rightTab.insertCharacterPane.index=4
addonSource=servers
rightTab.mathmlPane.atStart=true
rightTab.checkValidityPane.selected=false
rightTab.editPane.index=0
maximized=no
helperApplications.entries=
helperApplications.defaultViewer=xdg-open "%U"
startFromCaret=true
copyDocumentTemplate=false
rightTab.editAttributePane.selected=true
allowAdvancedXInclude=false
rightTab.textSearchReplacePane.atStart=false
rightTab.mathmlPane.selected=false
firstCharDisplayedByTable=0
addonInstallDir=best
warnAboutAdvancedXInclude=false
xxeVersion=8.2.0
addonURLs=http\://www.xmlmind.com/xmleditor/_usercontrib/list.xxe_addon\nhttp\://www.xmlmind.com/xmleditor/_download/list-${XXE_VERSION}.xxe_addon\nhttp\://www.xmlmind.com/archive/xmleditor/${XXE.VERSION}/list-${XXE_VERSION}.xxe_addon
rightTab.editAttributePane.index=2
geometry=0 0 900 700
rightTab.textSearchReplacePane.index=3
rightTab.checkValidityPane.index=5
rightPanes.width=0.275
rightTab.insertCharacterPane.selected=false
