#!/bin/sh
PATH=/usr/texbinxlingpaper:/usr/local/xlingpapertexbin:$PATH
cd "$2"
if [ -e xelatex.err ]; then
	rm xelatex.err
fi
xelatex -halt-on-error $1
if [ $? != "0" ]; then
	echo found error in TeX
	echo 'bad news' > xelatex.err
	exit 0
fi
xelatex -halt-on-error $1
if [ $? != "0" ]; then
	echo found error in TeX
	echo 'bad news' > xelatex.err
fi
cp "$3" "$4"
rm "$3"
