#!/bin/sh
PATH=$PATH:/usr/texbinxlingpaper
cd "$2"
if [ -e xelatex.err ]; then
	rm xelatex.err
fi
xelatex -halt-on-error $1
if [ $? != "0" ]; then
	echo found error in TeX
	echo 'bad news' > xelatex.err
fi



