#!/bin/sh
# following looks for XeLaTeX in the path and encloses the result in vertical bars
# without the vertical bars, we get a syntax error in the if statement if XeLaTeX is not in the path
PATH=$PATH:/usr/texbinxlingpaper2020:/usr/local/xlingpapertexbin2020
if [ "$(which xelatex)" != "" ]; then
	echo XLingPaper-Yes-XLingPaper
else
	echo XLingPaper-No-XLingPaper
fi

