#!/bin/sh
# following looks for Batik-rasterizer in the path and encloses the result in vertical bars
# without the vertical bars, we get a syntax error in the if statement if XeLaTeX is not in the path
PATH=$PATH:/usr/batik-raterizer
if [ "$(which batik-rasterizer)" != "" ]; then
	echo XLingPaper-Yes-XLingPaper
else
	echo XLingPaper-No-XLingPaper
fi
