# This workflow will sign the Windows full installer for XLingPaper.

name: XLingPaper Windows Full Installer Sign and Release

on:
  push:
    tags:
      - 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
      # to tag a commit, use "git tag v1.2.3"
      # when you then use "git push origin v1.2.3" this workflow will be invoked
#    paths:
#      - '.github/workflows/xlingpaper-windows-build-full-sign-release.yml'
#      - 'windows/XLingPaperXXEPersonalEditionFullSetup.nsi'

jobs:
  create_NSIS_installer:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true

    - name: Set and validate version
      uses: ./.github/actions/set-validate-version

    - name: 'Prepare for Java compilation'
      run: |
        cd javasrc\XLingPapExtensions
        mkdir class
        mkdir XXEJars
        cd XXEJars
        7z x ..\..\..\installers\XXE8Jars\XXE8Jars.7z -p${{ secrets.XXE82_INSTALLER }}
      shell: cmd

    - name: Set up JDK 8 and build with Ant
      uses: ./.github/actions/set-up-jdk-8-build-with-ant

    - name: 'create XLingPaper Configuration Folder'
      run: |
        mkdir XLingPaperConfiguration
        cd XLingPaperConfiguration
        mkdir XLingPap
        xcopy /f /s /e /y /i ..\batchfiles XLingPap\batchfiles
        xcopy /f /s /e /y /i ..\configuration XLingPap\configuration
        xcopy /f /s /e /y /i ..\css XLingPap\css
        xcopy /f /s /e /y /i ..\doc XLingPap\doc
        xcopy /f /s /e /y /i ..\dtds XLingPap\dtds
        xcopy /f /s /e /y /i ..\externalPackages XLingPap\externalPackages
        xcopy /f /s /e /y /i ..\localizations XLingPap\localizations
        xcopy /f /s /e /y /i ..\publisherstylesheets XLingPap\publisherstylesheets
        xcopy /f /s /e /y /i ..\templates XLingPap\templates
        xcopy /f /s /e /y /i ..\transforms XLingPap\transforms
        copy ..\XLingPap.jar XLingPap
        copy ..\XLingPap.sch XLingPap
        copy ..\XLingPap.xxe XLingPap
        copy ..\xlingpap.xxe_addon XLingPap
        copy ..\XLingPap_catalog.xml XLingPap
      shell: cmd

    - name: 'Install makensis (choco)'
      run: choco install nsis

    - env:
        NSISINST: C:\Program Files (x86)\NSIS
      shell: cmd
      run: |
        xcopy /f /s /e /y installers\windows\NSIS_Plugins\Include "%NSISINST%\Include\"
        xcopy /f /s /e /y installers\windows\NSIS_Plugins\Plugins "%NSISINST%\Plugins\x86-unicode\"
        7z x XXE8Installer\xxe82.7z -p${{ secrets.XXE82_INSTALLER }}
        "%NSISINST%\makensis" /V4 /DVERSION=${{ env.VERSION }}.0 installers\windows\XLingPaperXXEPersonalEditionFullSetup.nsi
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FullSetup
        path: installers/windows/XLingPaper*XXEPersonalEditionFullSetup.exe
        if-no-files-found: error

# old way to sign
  sign-full-setup-installer:
    name: Sign Windows XLingPaper full setup installer
    needs: create_NSIS_installer
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: FullSetup
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-full-setup-release:
    name: Create full setup Release
    needs: sign-full-setup-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: FullSetup

      - name: Create Full Setup Release
        uses: softprops/action-gh-release@v2
        with:
          files: XLingPaper*FullSetup.exe
          body: |
            Release for version ${{ github.ref }}
          draft: false

# new way to sign that is not yet usable
#  sign-full-setup-installer-release:
#    name: Sign Windows XLingPaper full setup Installer and Create Release
#    needs: create_NSIS_installer
#    runs-on: windows-latest
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          name: FullSetup
#      - name: Sign with Trusted Signing
#        uses: sillsdev/codesign/trusted-signing-action@v3
#        with:
#          credentials: ${{ secrets.TRUSTED_SIGNING_CREDENTIALS }}
#          files-folder: .
#          files-folder-filter: XLingPaper*FullSetup.exe
#          files-folder-recurse: true
#          files-folder-depth: 4
#          description:  'Release for version ${{ needs.build.outputs.version }} from branch ${{ github.ref }}'
#          description-url: 'https://software.sil.org/xlingpaper/'
#      - uses: actions/upload-artifact@v4
#        with:
#          name: XLingPaperFullSetupSigned
#          path: XLingPaper*FullSetup.exe
#          if-no-files-found: error
#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: XLingPaper*FullSetup.exe
#          body: |
#            Release for version ${{ github.ref }}
#          draft: false
